# Generated by Django 5.1.7 on 2025-06-05 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('senha', models.CharField(max_length=15)),
                ('idade', models.IntegerField()),
                ('telefone', models.CharField(max_length=14)),
                ('foto', models.ImageField(upload_to='')),
            ],
        ),
    ]
