# Generated by Django 5.1.7 on 2025-06-05 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0003_delete_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='pessoa',
            name='foto',
            field=models.ImageField(default='default.png', upload_to=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pessoa',
            name='senha',
            field=models.CharField(default='qwer1234', max_length=15),
            preserve_default=False,
        ),
    ]
